version: '3.1'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: YOURUSERNAME
      MYSQL_PASSWORD: YOURPASSWORD
      MYSQL_DATABASE: YOURDBNAME
    ports:
      - 3306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
